# Generated by Django 2.2.5 on 2021-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email_address', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_winner',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
