# Generated by Django 2.2.5 on 2021-05-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
